{% set name = "stackeddag" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stackeddag-{{ version }}.tar.gz
  sha256: 89404050364710f25188812248735fed34dae90c001e35e74bff7fc15a9f970b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydot

test:
  imports:
    - stackeddag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/junjihashimoto/py-stacked-dag
  summary: A visualization tool to show a ascii graph from Graphviz-Dot-file or Tensorflow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - junjihashimoto
